# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d363c6367b3dbc2e7e19e013d91bdb174754f94ffc696f2028a783623f1054e09678ca552b0f17eef37d8c423d872deb3e676c3ec055221de0b6c064f2ad20b

test:
  secret_key_base: 6627d11bb44a8df803fbf656c376618ca5f76d3db97dfac3bce9be1da7ea19125d5431ce3aeb72017eba15c3bfc266a31d6620a0ae3592d60adfb94a7b940822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
